server:
  port: 8762
  servlet:
    context-path: /
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/guoyutest?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  profiles:
    active: dev
  application:
    name: eureka-admin
logging:
  file:
    path: D:/data/boot
    name: boot.log
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.guoyu.imp.entity