server:
  port: 6060
  servlet:
    context-path: /es
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.0.115:9300
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/guoyutest?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  profiles:
    active: dev
  application:
    name: eureka-elk
#kafka配置
  kafka:
    bootstrap-servers: 192.168.0.114:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#es lasticsearch-rest-high-level-client方式
elasticsearch:
  host: 192.168.0.115:9200,192.168.0.116:9200,192.168.0.117:9200
logging:
  file:
    path: D:/data/boot
    name: boot.log