server:
  port: 7070
  servlet:
    context-path: /es
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.0.115:9300
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/guoyutest?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #出现错误时, 直接抛出异常
#es lasticsearch-rest-high-level-client方式
elasticsearch:
  host: 192.168.0.115:9200